### ISSUE TITLE
Parameter in the steps should also be taken into consideration in scenario outline

### ISSUE THREAD

**Issue by jadKhoury1** [Elie-A/Mocha-StepDefinition-Generator#9]
Scenario Outline: Sort Products
      Given user is on the "**Products**" page
      When user selects "<sort>" from the dropdown
      Then items are sorted by "<sort>" in "<order>" order

      Examples:
          | sort                | order |
          | Name (A to Z)       | ASC   |
          | Name (Z to A)       | DESC  |
          | Price (low to high) | ASC   |
          | Price (high to low) | DESC  |

**Comment by Elie-A** [comment]
Issue resolved
